#                                                                                                                                    
# Makefile for Elphel specific devices.                                                                                              
#                                                                                                                                    
                                                                                                                                     
obj-$(CONFIG_ELPHEL393)         += elphel393-pwr.o  
obj-$(CONFIG_ELPHEL393)         += elphel393-mem.o  
obj-$(CONFIG_ELPHELDRVONMICROZED)          += elphel393-mem.o  
