#                                                                                                                                    
# Makefile for Elphel specific devices.                                                                                              
#                                                                                                                                    
                                                                                                                                     
obj-$(CONFIG_ELPHEL393)           += elphel393-pwr.o  
obj-$(CONFIG_ELPHEL393)           += elphel393-mem.o  
obj-$(CONFIG_ELPHELDRVONMICROZED) += elphel393-mem.o
obj-$(CONFIG_ELPHEL393_INIT)      += elphel393-init.o   

#obj-$(CONFIG_ELPHEL393)           += framepars.o
#obj-$(CONFIG_ELPHEL393)           += sensor_common.o
#obj-$(CONFIG_ELPHEL393)           += quantization_tables.o
#obj-$(CONFIG_ELPHEL393)           += circbuf.o jpeghead.o

obj-$(CONFIG_ELPHEL393_EXTERNAL)  += framepars.o
obj-$(CONFIG_ELPHEL393_EXTERNAL)  += sensor_common.o
obj-$(CONFIG_ELPHEL393_EXTERNAL)  += quantization_tables.o
obj-$(CONFIG_ELPHEL393_EXTERNAL)  += circbuf.o jpeghead.o