#                                                                                                                                    
# Makefile for Elphel specific devices.                                                                                              
#                                                                                                                                    
                                                                                                                                     
obj-$(CONFIG_ELPHEL393)           += elphel393-pwr.o  
obj-$(CONFIG_ELPHEL393)           += elphel393-mem.o  
obj-$(CONFIG_ELPHELDRVONMICROZED) += elphel393-mem.o
obj-$(CONFIG_ELPHEL393_INIT)      += elphel393-init.o   

obj-$(CONFIG_ELPHEL393)           += x393.o
obj-$(CONFIG_ELPHEL393)           += sensor_i2c.o
obj-$(CONFIG_ELPHEL393)           += fpgajtag353.o
obj-$(CONFIG_ELPHEL393)           += clock10359.o
#fpgajtag-y := fpgajtag353.o x393.o 
#obj-$(CONFIG_ELPHEL393_EXTERNAL)  += fpgajtag.o

obj-$(CONFIG_ELPHEL393)           += exif393.o
obj-$(CONFIG_ELPHEL393)           += framepars.o
obj-$(CONFIG_ELPHEL393)           += sensor_common.o
obj-$(CONFIG_ELPHEL393)           += x393.o
obj-$(CONFIG_ELPHEL393)           += quantization_tables.o
obj-$(CONFIG_ELPHEL393)           += circbuf.o
obj-$(CONFIG_ELPHEL393)           += jpeghead.o

obj-$(CONFIG_ELPHEL393)           += gamma_tables.o
obj-$(CONFIG_ELPHEL393)           += histograms.o
obj-$(CONFIG_ELPHEL393)           += pgm_functions.o
obj-$(CONFIG_ELPHEL393)           += mt9x001.o
obj-$(CONFIG_ELPHEL393)           += mt9f002.o
obj-$(CONFIG_ELPHEL393)           += lepton.o
obj-$(CONFIG_ELPHEL393)           += multi10359.o
obj-$(CONFIG_ELPHEL393)           += imu_log393.o

obj-$(CONFIG_ELPHEL393)           += cxi2c.o
obj-$(CONFIG_ELPHEL393)           += x393_videomem.o
obj-$(CONFIG_ELPHEL393)           += detect_sensors.o
obj-$(CONFIG_ELPHEL393)           += x393_fpga_functions.o
obj-$(CONFIG_ELPHEL393)           += klogger_393.o